name: semaphoreci_flutter_demo
description: SemaphoreCI Flutter Demo

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  http: <latest_version>
  flutter:
    sdk: flutter
  provider: ^5.0.0
  camera:
  path_provider:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
