# THis is the default workflow for python that I have modified
name: Python_Backend

# conditional activation
on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**.py'
  
  # for testing purposes
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_python:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install prospector[with_everything] pytest coverage
        # librarys like deepface
        pip install -r .github/workflows/requirments.txt
    - name: Linting Uisng Prospector
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # TODO make better options.
        cd backend
        # we want it to fail on errors, covered by the linter
        prospector
        cd ..
    - name: Test and coverage
      run: |
        coverage run --rcfile=.github/workflows/.coveragerc -m pytest backend/test/
